### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by praisethemoon** [upbit/opencl-helper#1]
Hello, 

Thank you for writing this sweet lib. I intend to use it in my FOSS project, but I would like to know which license do you intent to use for this lib.

Cheers! 🍺

**Comment by upbit** [comment]
No License. Please feel free to use it

**Comment by praisethemoon** [comment]
Awesome, I suggest adding WTFPL License: https://en.wikipedia.org/wiki/WTFPL :smile: 

Best Regards.

**Comment by upbit** [comment]
Thanks, added [WTFPL License](https://github.com/upbit/opencl-helper/blob/master/LICENSE)
